- name: Disable SELinux (Amazon Linux)
  when: ansible_os_family == "RedHat"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: true  

- name: Install curl (dependency for Netdata)
  apt:
    name: curl
    state: present
  when: ansible_os_family == "Debian"
